/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aldisp;

public class AldispRunner {

    public static void main(String[] args) {
        System.out.println("nothing to see here. have a look at the unit tests!");
    }
}
