/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aldisp;

public class AldispRunner {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new AldispRunner().getGreeting());
    }
}
